A corregir por: ...

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,17 @@
 #!/bin/sh
 
 # Comprobar que el mensaje de commit contiene la frase "A corregir por: ..."
+current_branch=$(git symbolic-ref-short HEAD)
 
-commit_message=$(git log --oneline -1)
+if [[ "$current_branch" == "hotfix/mejorasV_1_0" ]]; then
+    commit_msg_file="$1"
+    commit_msg=$(cat "$commit_msg_file")
 
-if [[ ! $commit_message =~ "A corregir por:" ]]; then
-  echo "El mensaje de commit debe contener la frase 'A corregir por: ...'"
-  exit 1
+    commit_message=$(git log --oneline -1)
+
+    if [[ ! $commit_message == "A corregir por: "* ]]; then
+    echo "El mensaje de commit debe contener la frase 'A corregir por: ...'"
+    echo "Abortando el commit."
+    exit 1
+    fi
 fi
