usuario1

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -19,9 +19,11 @@ if [[ "$current_branch" == "hotfix/mejorasV_1_0" ]]; then
     # commit_msg=$(cat "$commit_msg_file")
 
     echo "grep"
-    if  grep -q "A corregir por:"; then
-    echo "El mensaje de commit debe contener la frase 'A corregir por: ...'"
-    echo "Abortando el commit."
-    exit 1
-    fi
+    for file in $(git diff --cached --name-only); do
+        if  grep -q "A corregir por:"; then
+        echo "El mensaje de commit debe contener la frase 'A corregir por: ...'"
+        echo "Abortando el commit."
+        exit 1
+        fi
+    done
 fi
